name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
        toolchain: [nightly, beta]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install alsa
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

      - name: Install udev
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

      - name: Use Rust Cache
        if: ${{ runner.os == 'Linux' }}
        uses: Swatinem/rust-cache@v2.0.1

      - name: Run cargo check --all-targets w/ -D warnings
        run: cargo check --all-targets
        # We should add this later: env:
          #RUSTFLAGS: "-D warnings"

      - name: Run cargo test w/ -D warnings
        if: ${{ runner.os == 'Linux' }}
        run: cargo test headless -- --test-threads=1
        #env:
          #RUSTFLAGS: "-D warnings"

  rustfmt:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get nightly Rust toolchain with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt --all -- --check
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get stable Rust toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Install alsa
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

      - name: Install udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

      - name: Run cargo clippy --package game --all-targets -- -D warnings
        run: cargo clippy --package game --all-targets #-- -D warnings