name: Release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-latest ]
        toolchain: [ nightly ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install alsa
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

      - name: Install udev
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

      - name: Use Rust Cache
        if: ${{ runner.os == 'Linux' }}
        uses: Swatinem/rust-cache@v2.0.1

      - name: Run build --release
        run: cargo build --release

      - name: Release Linux
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          files: |
            target/release/game
            assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Windows
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          files: |
            target/release/game.exe
            assets
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}